import type { FlavorSet } from '../models/product.model';

const PRODUCT_IMAGE_FILES: Record<string, string> = {
  'Chocolate Fudge Brownie': 'Chocolate/Chocolate Fudge Brownie.png',
  'Double Dark Chocolate': 'Chocolate/Double Dark Chocolate.jpg',
  'Chocolate Therapy': 'Chocolate/Chocolate Therapy.png',
  'Mexican Chocolate': 'Chocolate/Mexican Chocolate.jpg',
  'Phish Food Style': 'Chocolate/Phish Food Style.png',
  'Rocky Road': 'Chocolate/Rocky Road.jpg',
  'Chocolate Peanut Butter Cup': 'Chocolate/Chocolate Peanut Butter Cup.png',
  'New York Super Fudge Chunk': 'Chocolate/New York Super Fudge Chunk.png',
  'Classic Madagascar Vanilla': 'Vanilla/Classic Madagascar Vanilla.png',
  'Vanilla Bean Supreme': 'Vanilla/Vanilla Bean Supreme.png',
  'French Vanilla Custard': 'Vanilla/French Vanilla Custard.png',
  'Vanilla Cookie Crumble': 'Vanilla/Vanilla Cookie Crumble.png',
  'Vanilla Caramel Swirl': 'Vanilla/Vanilla Caramel Swirl.png',
  'Tahitian Vanilla Bourbon': 'Vanilla/Tahitian Vanilla Bourbon.png',
  'Vanilla Toffee Crunch': 'Vanilla/Vanilla Toffee Crunch.webp',
  'Vanilla Honeycomb': 'Vanilla/Vanilla Honeycomb.png',
  'Strawberry Cheesecake': 'Strawberry/Strawberry Cheesecake.png',
  'Strawberry Shortcake': 'Strawberry/Strawberry Shortcake.png',
  'Wild Strawberry Swirl': 'Strawberry/Wild Strawberry Swirl.png',
  'Strawberry Balsamic': 'Strawberry/Strawberry Balsamic.png',
  'Strawberry Fields Forever': 'Strawberry/Strawberry Fields Forever.webp',
  'Strawberry Yogurt Blend': 'Strawberry/Strawberry Yogurt Blend.png',
  'Strawberry Basil': 'Strawberry/Strawberry Basil.png',
  'Strawberry Cream Delight': 'Strawberry/Strawberry Cream Delight.png',
  'Classic Mango Sorbet': 'Mango/Classic Mango Sorbet.png',
  'Mango Graham': 'Mango/Mango Graham.png',
  'Mango Sticky Rice': 'Mango/Mango Sticky Rice.png',
  'Mango Chili Lime': 'Mango/Mango Chili Lime.png',
  'Mango Coconut Cream': 'Mango/Mango Coconut Cream.png',
  'Mango Cheesecake': 'Mango/Mango Cheesecake.png',
  'Mango Tango Twist': 'Mango/Mango Tango Twist.png',
  'Mango Passionfruit': 'Mango/Mango Passionfruit.png',
  'Classic Ube Halaya': 'Ube/Classic Ube Halaya.png',
  'Ube Cheese': 'Ube/Ube Cheese.png',
  'Ube Macapuno': 'Ube/Ube Macapuno.png',
  'Ube Coconut Swirl': 'Ube/Ube Coconut Swirl.png',
  'Ube Cookies and Cream': 'Ube/Ube Cookies and Cream.png',
  'Ube Leche Flan': 'Ube/Ube Leche Flan.png',
  'Ube Pandan Fusion': 'Ube/Ube Pandan Fusion.png',
  'Ube Halo-Halo Style': 'Ube/Ube Halo-Halo Style.png',
  'Mint Chocolate Chip': 'Mint/Mint Chocolate Chip.png',
  'Mint Fudge Swirl': 'Mint/Mint Fudge Swirl.png',
  'Mint Oreo Crumble': 'Mint/Mint Oreo Crumble.png',
  'Mint Chocolate Cookie': 'Mint/Mint Chocolate Cookie.png',
  'Peppermint Bark': 'Mint/Peppermint Bark.png',
  'Mint Cheesecake': 'Mint/Mint Cheesecake.png',
  'Mint Brownie Batter': 'Mint/Mint Brownie Batter.png',
  'Mint Coconut Twist': 'Mint/Mint Coconut Twist.png',
  'Classic Coffee Bean': 'Coffee/Classic Coffee Bean.png',
  'Mocha Almond Fudge': 'Coffee/Mocha Almond Fudge.png',
  'Cappuccino Crunch': 'Coffee/Cappuccino Crunch.png',
  'Coffee Caramel Swirl': 'Coffee/Coffee Caramel Swirl.png',
  'Tiramisu Style': 'Coffee/Tiramisu Style.png',
  'Coffee Toffee Bar': 'Coffee/Coffee Toffee Bar.png',
  'Vietnamese Coffee': 'Coffee/Vietnamese Coffee.png',
  'Coffee Chocolate Chip': 'Coffee/Coffee Chocolate Chip.png',
  'Classic Cookies and Cream': 'Cookies and Cream/Classic Cookies and Cream.png',
  'Double Stuffed Cookie': 'Cookies and Cream/Double Stuffed Cookie.png',
  'Cookie Butter Swirl': 'Cookies and Cream/Cookie Butter Swirl.png',
  'Cookies and Caramel': 'Cookies and Cream/Cookies and Caramel.png',
  'Chocolate Chip Cookie Dough': 'Cookies and Cream/Chocolate Chip Cookie Dough.jpg',
  'Birthday Cake Cookie': 'Cookies and Cream/Birthday Cake Cookie.png',
  'Cookies and Cream Fudge': 'Cookies and Cream/Cookies and Cream Fudge.png',
  'Peanut Butter Cookie Crunch': 'Cookies and Cream/Peanut Butter Cookie Crunch.jpg',
};

export function getProductImageUrl(
  variantName: string,
  imageUrl?: string,
  _setNumber?: FlavorSet
): string {
  if (imageUrl) return imageUrl;
  const imageFile = PRODUCT_IMAGE_FILES[variantName];
  return imageFile ? `/assets/images/Products/${imageFile}` : '';
}
